In [2]:
import numpy as np
import time

In [3]:
arr=np.array([1,34,2,2,4])
print(arr,type(arr))

[ 1 34  2  2  4] <class 'numpy.ndarray'>


In [4]:

# execution performance
size = 10_000_000

# python list
py_list = list(range(size))

start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()

print(f"python list time = {end-start} seconds")

# numpy arrays
np_arr = np.array(py_list)

start = time.time()
sq_array = np_arr ** 2
end = time.time()

print(f"numpy array time = {end-start} seconds")

python list time = 0.24060893058776855 seconds
numpy array time = 0.016117095947265625 seconds


In [5]:
#memory
import sys
print(f'python list size={sys.getsizeof(py_list)} bytes')
print(f'numpy array size={np_arr.nbytes}bytes')

python list size=80000056 bytes
numpy array size=80000000bytes


In [6]:
# create from list
arr=np.array([1,2,3,44,3])
print(arr,type(arr))
arr2=np.array([1,23,2,7,"prime"])
print(arr2,type(arr2))

arr2D=np.array([[2,4,6],[1,2,3],[7,8,9],[2,33,2]])
print(arr2D, arr2D.shape)

[ 1  2  3 44  3] <class 'numpy.ndarray'>
['1' '23' '2' '7' 'prime'] <class 'numpy.ndarray'>
[[ 2  4  6]
 [ 1  2  3]
 [ 7  8  9]
 [ 2 33  2]] (4, 3)


In [7]:
# create
arr1=np.zeros((2,3), dtype="int64") #prefill
print(arr1,arr1.shape)

arr2=np.ones((2,), dtype="int64") #prefill
print(arr2,arr2.shape)

arr3=np.full((2,3),10) #prefill with value
print(arr3,arr3.shape)

arr3=np.full((3,4),10) #prefill with value
print(arr3,arr3.shape)

arr4=np.eye(3) #identity matrix
print(arr4,arr4.shape)

arr5=np.arange(0,12,2) #range elememnt
print(arr5,arr5.shape)

arr6=np.linspace(1,50,3) # evenly spaced element
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1 1] (2,)
[[10 10 10]
 [10 10 10]] (2, 3)
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[ 1.  25.5 50. ] (3,)


In [8]:
#properties
arr=np.array([[2,3,4],[3,2,4],[2,2,1],[2,7,6]])
print(arr.size)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)

12
(4, 3)
2
int64
[[2. 3. 4.]
 [3. 2. 4.]
 [2. 2. 1.]
 [2. 7. 6.]] float64


In [9]:
#operation on arrays
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[2,4,2]])
reshaped=arr.reshape(3,4)
print(reshaped,reshaped.shape)

flattended=arr.flatten() #2d---> 1d
print(flattended,flattended.shape)

[[1 2 3 4]
 [5 6 7 8]
 [9 2 4 2]] (3, 4)
[1 2 3 4 5 6 7 8 9 2 4 2] (12,)


In [10]:
# fancing indexing,boolean indexing
arr=np.array([1,2,3,4,5])
idx=[0,1,4]
print(arr[idx])

print(arr[arr>3])
print(arr[arr%2==0])
print(arr[arr%2!=0])
    

[1 2 5]
[4 5]
[2 4]
[1 3 5]


In [11]:
#slicing
arr=np.array([1,2,3,4,5])
print(arr[1:4])# [start,end,step]
print(arr[1:])
print(arr[1:2])
print(arr[:5])

[2 3 4]
[2 3 4 5]
[2]
[1 2 3 4 5]


In [12]:
#copy vs view
num=[1,2,3,4,5]
sub_num=num[1:3]
print(sub_num)
sub_num[0]=100
print(sub_num)
print(num)

num=np.array([1,2,3,4,5])
sub_num=num[1:3]
print(sub_num)
sub_num[0]=100
print(sub_num)
print(num)

[2, 3]
[100, 3]
[1, 2, 3, 4, 5]
[2 3]
[100   3]
[  1 100   3   4   5]


In [13]:
#Data types
arr1= np.array([1,2.5,3,5j])
arr2= np.array([1,2.5,3,5j])
arr3=np.array([1,"prime",{3,4},3.14])
print(arr3,arr3.dtype)
print(arr1+arr2)
print(arr1,arr1.dtype)

[1 'prime' {3, 4} 3.14] object
[2. +0.j 5. +0.j 6. +0.j 0.+10.j]
[1. +0.j 2.5+0.j 3. +0.j 0. +5.j] complex128


In [20]:
#Multidimensional array
arr2D=np.array([[1,2,4],[4,5,4],[53,5,3]])
print(arr2D)

print(np.sum(arr2D))

sumOfColumn=np.sum(arr2D,axis=0)
print(sumOfColumn)

sumOfrows=np.sum(arr2D,axis=1)
print(sumOfrows)

print(arr2D[0:2,1:2])

[[ 1  2  4]
 [ 4  5  4]
 [53  5  3]]
81
[58 12 11]
[ 7 13 61]
[[2]
 [5]]


In [32]:
#3D array
arr3d = np.array([[[1, 2], [3, 4], [5, 6]],[[7, 8], [9, 10], [11, 12]]])

print(arr3d,arr3d.shape)

#indexing
print(arr3d[1,1,0])

#slicing
print(arr3d[:,0,:])#first row from both layer
print(arr3d[:,:,0])#first coloumn from both layer


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


In [34]:
#vectorization
arr=np.array([1,2,3,6,3])
arr2=np.array([3,2,4,2,1])
print(arr+arr2)

[4 4 7 8 4]


In [44]:
#broadcating
arr=np.array([[1,2,3,6,3],[1,2,3,4,5],[1,2,3,4,5]])
arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr.shape)
print(arr2.shape)

(3, 5)
(2, 5)


In [47]:
#normalize
arr=np.array([[1,2],[3,4]])
mean=np.mean(arr)
std=np.std(arr)
normalized_arr=(arr-mean)/std
print(normalized_arr)

print(mean)
print(std)
print(np.sqrt(5/4))

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895
1.118033988749895


In [48]:
#Mathematical Function

#aggreation

arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))      # Sum
print(np.prod(arr))     # Product
print(np.min(arr))      # Minimum value
print(np.max(arr))      # Maximum value
print(np.argmin(arr))   # Index of minimum value
print(np.argmax(arr))   # Index of maximum value

print(np.mean(arr))     # Mean
print(np.std(arr))      # Standard deviation
print(np.median(arr))   # Median
print(np.var(arr))      # Variance

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [51]:
# Power Function

arr = np.array([1, 2, 3, 4, 5])
print(np.sqrt(arr))
print(np.square(arr))
print(np,pow(arr,3))

[1.         1.41421356 1.73205081 2.         2.23606798]
[ 1  4  9 16 25]
<module 'numpy' from '/opt/anaconda3/lib/python3.13/site-packages/numpy/__init__.py'> [  1   8  27  64 125]


In [54]:
# log

arr = np.array([1, 2, 3, 4, 5]) 
print(np.log(arr))
print(np.log10(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [63]:
#Round

print(np.round(3.5))
print(np.ceil(3.4))
print(np.floor(3.5))
print(np.trunc(3.5))

arr = np.array([1, 2,3,-2, 3, 4, 5]) 
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

4.0
4.0
3.0
3.0
[-2  1  2  3  4  5]
[-2  1  2  3  3  4  5]
[1 2 3 2 3 4 5]
