In [2]:
import numpy as np
import time

In [3]:
arr=np.array([1,34,2,2,4])
print(arr,type(arr))

[ 1 34  2  2  4] <class 'numpy.ndarray'>


In [4]:

# execution performance
size = 10_000_000

# python list
py_list = list(range(size))

start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()

print(f"python list time = {end-start} seconds")

# numpy arrays
np_arr = np.array(py_list)

start = time.time()
sq_array = np_arr ** 2
end = time.time()

print(f"numpy array time = {end-start} seconds")

python list time = 0.21037912368774414 seconds
numpy array time = 0.008928060531616211 seconds


In [5]:
#memory
import sys
print(f'python list size={sys.getsizeof(py_list)} bytes')
print(f'numpy array size={np_arr.nbytes}bytes')

python list size=80000056 bytes
numpy array size=80000000bytes


In [16]:
# create from list
arr=np.array([1,2,3,44,3])
print(arr,type(arr))
arr2=np.array([1,23,2,7,"prime"])
print(arr2,type(arr2))

arr2D=np.array([[2,4,6],[1,2,3],[7,8,9],[2,33,2]])
print(arr2D, arr2D.shape)

[ 1  2  3 44  3] <class 'numpy.ndarray'>
['1' '23' '2' '7' 'prime'] <class 'numpy.ndarray'>
[[ 2  4  6]
 [ 1  2  3]
 [ 7  8  9]
 [ 2 33  2]] (4, 3)


In [32]:
# create
arr1=np.zeros((2,3), dtype="int64") #prefill
print(arr1,arr1.shape)

arr2=np.ones((2,), dtype="int64") #prefill
print(arr2,arr2.shape)

arr3=np.full((2,3),10) #prefill with value
print(arr3,arr3.shape)

arr3=np.full((3,4),10) #prefill with value
print(arr3,arr3.shape)

arr4=np.eye(3) #identity matrix
print(arr4,arr4.shape)

arr5=np.arange(0,12,2) #range elememnt
print(arr5,arr5.shape)

arr6=np.linspace(1,50,3) # evenly spaced element
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1 1] (2,)
[[10 10 10]
 [10 10 10]] (2, 3)
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[ 1.  25.5 50. ] (3,)


In [34]:
#properties
arr=np.array([[2,3,4],[3,2,4],[2,2,1],[2,7,6]])
print(arr.size)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)

12
(4, 3)
2
int64
[[2. 3. 4.]
 [3. 2. 4.]
 [2. 2. 1.]
 [2. 7. 6.]] float64
